version: "3.4"

services:
  hydrant:
    env_file: .env
    image: "ghcr.io/outsideopen/delta-collectors:${DELTA_VERSION:-latest}"
    logging:
      driver: json-file
      options:
        max-size: 10m
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./data:/app/data

  canary:
    env_file: .env
    image: "ghcr.io/outsideopen/opencanary:${CANARY_VERSION:-latest}"
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - "21:21"
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./opencanary.conf:/opencanary/opencanary.conf
