version: "3.4"

services:
  hydrant:
    env_file: .env
    image: "ghcr.io/outsideopen/delta-collectors:${DELTA_VERSION:-latest}"
    logging:
      driver: json-file
      options:
        max-size: 100m
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /var/run/dbus:/var/run/dbus

  canary:
    env_file: .env
    image: "ghcr.io/outsideopen/opencanary:${CANARY_VERSION:-latest}"
    logging:
      driver: json-file
      options:
        max-size: 100m
    ports:
      - "21:21"
      - "22:22"
      - "80:80"
      - "443:443"
      - "3389:3389"
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./opencanary.conf:/opencanary/opencanary.conf
