name: CI
on:
  push:
    branches-ignore:
      - main
  pull_request:
    types:
      - closed
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - run: pip install flit
      - run: flit install --deps all --symlink
      - run: pytest
