name: Lint
on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [closed]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: psf/black@26.3.0

